# Generated by Django 2.1.5 on 2019-04-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.CharField(max_length=50)),
                ('y_axis', models.IntegerField()),
            ],
        ),
    ]
