# Generated by Django 2.1.5 on 2019-04-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dummy_for_histo_and_cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('x_axis_keyword', models.CharField(max_length=50)),
                ('y_axis_quantity', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='dummy',
        ),
    ]
