# Generated by Django 2.1.5 on 2019-05-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20190411_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeGraph_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top5_keyword', models.CharField(max_length=50)),
                ('y_axis_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeGraph_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top5_keyword', models.CharField(max_length=50)),
                ('y_axis_quantity', models.IntegerField()),
            ],
        ),
    ]
