# Generated by Django 2.1.5 on 2019-05-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20190531_0232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeGraph_1',
        ),
        migrations.DeleteModel(
            name='TimeGraph_2',
        ),
    ]
