# Generated by Django 2.1.5 on 2019-06-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_timegraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy_for_histo_and_cloud',
            name='company_name',
            field=models.CharField(choices=[('1', 'LG CNS'), ('2', '네이버'), ('3', '삼성 SDS'), ('4', '쿠팡'), ('5', '구글 코리아'), ('6', '카카오'), ('7', '배달의 민족'), ('8', 'AWS'), ('9', 'SK C&C'), ('10', '퀄컴')], max_length=100),
        ),
        migrations.AlterField(
            model_name='timegraph',
            name='company_name',
            field=models.CharField(choices=[('1', 'LG CNS'), ('2', '네이버'), ('3', '삼성 SDS'), ('4', '쿠팡'), ('5', '구글 코리아'), ('6', '카카오'), ('7', '배달의 민족'), ('8', 'AWS'), ('9', 'SK C&C'), ('10', '퀄컴')], max_length=100),
        ),
    ]
