# Generated by Django 2.1.5 on 2019-06-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_auto_20190606_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy_for_histo_and_cloud',
            name='company_name',
            field=models.CharField(choices=[('1', 'CNS'), ('2', '네이버'), ('3', 'SDS'), ('4', '쿠팡'), ('5', '구글'), ('6', '카카오'), ('7', '배민'), ('8', 'AWS'), ('9', 'C&C'), ('10', '퀄컴')], max_length=100),
        ),
        migrations.AlterField(
            model_name='timegraph',
            name='company_name',
            field=models.CharField(choices=[('1', 'CNS'), ('2', '네이버'), ('3', 'SDS'), ('4', '쿠팡'), ('5', '구글'), ('6', '카카오'), ('7', '배민'), ('8', 'AWS'), ('9', 'C&C'), ('10', '퀄컴')], max_length=100),
        ),
    ]
