# Generated by Django 2.1.5 on 2019-06-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_auto_20190608_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timegraph',
            name='time',
            field=models.CharField(choices=[('1', '2018 1-3월'), ('2', '2018 4-6월'), ('3', '2018 7-9월'), ('4', '2018 10-12월'), ('5', '2019 1-3월'), ('6', '2019 4-6월')], max_length=2),
        ),
    ]
