# Generated by Django 2.1.5 on 2019-06-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_auto_20190608_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='histo_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(choices=[('1', 'CNS'), ('2', '네이버'), ('3', 'SDS'), ('4', '쿠팡'), ('5', '구글'), ('6', '카카오'), ('7', '배민'), ('8', 'AWS'), ('9', 'C&C'), ('10', '퀄컴')], max_length=100)),
                ('x_axis_keyword', models.CharField(max_length=50)),
                ('y_axis_quantity', models.IntegerField()),
                ('related_keyword_1', models.CharField(blank=True, max_length=20, null=True)),
                ('related_keyword_2', models.CharField(blank=True, max_length=20, null=True)),
                ('related_keyword_4', models.CharField(blank=True, max_length=20, null=True)),
                ('related_keyword_5', models.CharField(blank=True, max_length=20, null=True)),
                ('related_keyword_3', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
